project:
  type: website

website:
  title: "Alexssandrosilv.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    html-math-method: katex                                            # --> Método de renderização matemática (KaTeX é leve e rápido)
    theme: 
      light: [flatly]                                                  # -----> Tema visual para o modo claro (Flatly: moderno e claro)
      dark: [cyborg]                                                   # -----> Tema visual para o modo escuro (Cyborg: fundo escuro e letras claras)
    # css: styles.css
    toc: true




