project:
  type: website

website:
  title: ""
  description: Descrição do site
  navbar:
    left:
      - href: mlg.qmd
        text: Modelos Lineares Generalizados (MLG)
      - href: imd.qmd
        text: Introdução à Mineração de Dados (IMD)
      - href: int_bayes.qmd
        text: Introdução à Inferência Bayesiana
      - href: resumo.qmd
        text: Lista de Café da Manhã
      - href: about.qmd
        text: Sobre 

format: 
  html:                                                                # --> Formatação específica para saída em HTML
    toc: true                                                          # --> Ativa o sumário (índice)
    #toc-expand: 3                                                      # --> Define quantos níveis do sumário aparecem abertos por padrão
    toc-title: Sumário                                                 # --> Título exibido no topo do sumário
    #page-layout: custom 
    #toc-depth: 3                                                       # --> Quantos níveis hierárquicos de seções aparecerão no sumário
    html-math-method: katex                                            # --> Método de renderização matemática (KaTeX é leve e rápido)
    toc-location: right                                                # --> Coloca o sumário à direita do conteúdo
    number-sections: true                                              # --> Numera automaticamente as seções e subseções
    code-fold: true                                                    # --> Código-fonte recolhido por padrão (com opção de expandir)
    fontsize: 0.9em                                                    # --> Define o tamanho da fonte como 90% do padrão
    #linestretch: 1.7                                                   # --> Controla o espaçamento entre linhas
    #max-width: null                                                  # --> Define largura máxima MUITO ampla (pode ser ajustado para ~80em, se desejar)
    margin-left: 0em                                                   # --> Margem esquerda do conteúdo (0 = sem margem)
    margin-right: 0em                                                  # --> Margem direita do conteúdo (0 = sem margem)
    margin-bottom: 0em                                                 # --> Margem inferior (sem espaço extra abaixo)
    margin-top: -1em                                                   # --> Margem superior negativa (levemente "sobe" o conteúdo)
    #df_print: paged                                                    # --> Impressão paginada de dataframes, se ativado
    #highlight: espresso                                                # --> Tema de cores para realce de código (sintaxe)
    #smooth_scroll: TRUE                                                # --> Ativa rolagem suave
    #css: styles.css                                                   # --> Aponta para um arquivo personalizado de estilo (opcional, se existir)
    theme: 
      light: [flatly]                                                  # -----> Tema visual para o modo claro (Flatly: moderno e claro)
      dark: [cyborg]                                                   # -----> Tema visual para o modo escuro (Cyborg: fundo escuro e letras claras)
